export const SRS = {
  INITIAL_EASE_FACTOR: 2.0,
  MIN_EASE_FACTOR: 1.3,
  MAX_EASE_FACTOR: 2.5,

  WRONG_EASE_DELTA: -0.2,
  HARD_EASE_DELTA: -0.15,
  CORRECT_EASE_DELTA: 0.1,

  HARD_INTERVAL_MULTIPLIER: 0.5,

  MASTERED_REPETITIONS: 5,
  MASTERED_MIN_INTERVAL: 21,
} as const
